import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    exclude: ['tests/**', 'node_modules/**', 'out/**', 'electron/dist/**', 'electron/src/**', '.stryker-tmp/**'],
    setupFiles: ['./src/__tests__/setup.ts'],
    // Vitest 4: poolOptions 已移除，maxWorkers/minWorkers 为顶层配置
    // 限制并发为 2，避免高内存场景下的资源竞争
    maxWorkers: 2,
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html", "lcov"],
      include: [
        "src/domain/**/*.ts",
        "src/infrastructure/**/*.ts",
        "src/modules/**/*.ts",
        "src/shared/**/*.ts",
        "src/config/**/*.ts",
      ],
      exclude: [
        "src/__tests__/",
        "**/__tests__/**",
        "**/*.d.ts",
        "**/*.config.*",
        "**/index.ts",
        "src/domain/ports/",
        "src/modules/**/presentation/**",
        "src/modules/**/constants.ts",
        "src/shared/ui/**",
        "src/shared/presentation/**",
        "src/shared/types/**",
        "src/infrastructure/monitoring/**",
        "src/infrastructure/server/**",
        "src/infrastructure/database/**",
        "src/infrastructure/di/container.ts",
        "src/infrastructure/di/registry.ts",
        "src/infrastructure/network/**",
        "src/infrastructure/api/**",
        "src/infrastructure/ai-providers/api-config/server*.ts",
        "src/infrastructure/ai-providers/api-config/init.ts",
        "src/infrastructure/ai-providers/api-config/migrate.ts",
        "src/infrastructure/ai-providers/api-config/templates.ts",
        "src/shared/hooks/use-global-keyboard-actions.ts",
        "src/shared/hooks/use-keyboard-shortcuts.ts",
        "src/shared/hooks/use-memory-monitor.ts",
        "src/shared/hooks/use-network-monitor.ts",
        "src/shared/hooks/use-current-time.ts",
        "src/shared/utils/performance.ts",
        "src/shared/utils/confirm.tsx",
        "src/shared/utils/file-download.ts",
        "src/shared/video-utils/video-frame-extractor.ts",
        "src/modules/**/hooks/use-*.ts",
        "src/modules/persistence/hooks/**",
        "src/modules/video/task-management/hooks/internals/*.ts",
        "src/modules/shot/shot-generation/**",
        "src/modules/shot/shot-reference/**",
        "src/modules/shot/element-binding/use-element-binding.ts",
        "src/modules/shot/feature-extraction/**",
        "src/modules/storyboard/planning/hooks/use-story-planner.ts",
        "src/modules/storyboard/beat-editor/hooks/use-asset-loader.ts",
        "src/modules/storyboard/prompt-editor/hooks/**",
        "src/modules/storyboard/template/story-templates.ts",
        "src/modules/asset/hooks/**",
        "src/modules/sync/engine/server-store.ts",
        "src/shared/hooks/use-debounced-state.ts",
        "src/shared/sql-safety/schema-registry.ts",
        "src/shared/video-utils/video-codec.ts",
        "src/shared/video-utils/provider-codecs.ts",
        "src/config/constants.ts",
      ],
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
        perFile: false,
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      // @huggingface/transformers 是可选依赖，未安装时 vitest 模块解析失败。
      // 指向测试 mock，运行时 loadPipeline() 的 try/catch 会安全降级。
      '@huggingface/transformers': path.resolve(__dirname, './src/__tests__/mocks/huggingface-transformers-mock.ts'),
    },
  },
});
