import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    exclude: ['tests/**', 'node_modules/**', 'dist/**', '.next/**', 'electron/dist/**'],
    setupFiles: ['./src/__tests__/setup.ts'],
    pool: "forks",
    maxWorkers: 2,
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html", "lcov"],
      include: [
        "src/domain/schemas/**/*.ts",
        "src/domain/services/beat-workflow-service.ts",
        "src/domain/services/reference-resolver.ts",
        "src/domain/types/result.ts",
        "src/domain/types/sync.ts",
        "src/domain/types/index.ts",
        "src/domain/utils/**/*.ts",
        "src/infrastructure/di/**/*.ts",
        "src/infrastructure/storage/core.ts",
        "src/infrastructure/storage/sqlite-core.ts",
        "src/infrastructure/storage/video-cache.ts",
        "src/infrastructure/storage/video-tasks.ts",
        "src/infrastructure/storage/stories.ts",
        "src/infrastructure/storage/elements.ts",
        "src/infrastructure/storage/characters.ts",
        "src/infrastructure/storage/scenes.ts",
        "src/infrastructure/ai-providers/core.ts",
        "src/infrastructure/ai-providers/api-cache.ts",
        "src/infrastructure/ai-providers/model-capabilities.ts",
        "src/infrastructure/ai-providers/model-adapter/index.ts",
        "src/infrastructure/ai-providers/image.ts",
        "src/infrastructure/ai-providers/errors.ts",
        "src/infrastructure/ai-providers/api-config/detect.ts",
        "src/infrastructure/ai-providers/api-config/templates.ts",
        "src/infrastructure/network/circuit-breaker.ts",
        "src/infrastructure/network/retry-executor.ts",
        "src/infrastructure/video-utils/video-codec.ts",
        "src/infrastructure/secure-storage.ts",
        "src/modules/**/services/**/*.ts",
        "src/modules/character/constants.ts",
        "src/modules/scene/constants.ts",
        "src/shared/error-handler.ts",
        "src/shared/error-logger.ts",
        "src/shared/event-bus.ts",
        "src/shared/event-types.ts",
        "src/shared/utils/image-url.ts",
        "src/shared/utils/utils.ts",
        "src/config/constants.ts",
      ],
      exclude: [
        "src/__tests__/",
        "**/*.d.ts",
        "**/*.config.*",
        "src/domain/ports/",
      ],
      thresholds: {
        branches: 70,
        functions: 70,
        lines: 70,
        statements: 70,
        perFile: true,
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
