import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    exclude: ['tests/**', 'node_modules/**', 'out/**', 'electron/dist/**', 'src/__tests__/e2e/**'],
    setupFiles: ['./src/__tests__/setup.ts'],
    pool: "forks",
    maxWorkers: 2,
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html", "lcov"],
      include: [
        "src/domain/**/*.ts",
        "src/infrastructure/**/*.ts",
        "src/modules/**/*.ts",
        "src/shared/**/*.ts",
        "src/config/**/*.ts",
      ],
      exclude: [
        "src/__tests__/",
        "**/__tests__/**",
        "**/*.d.ts",
        "**/*.config.*",
        "**/index.ts",
        "src/domain/ports/",
        "src/modules/**/presentation/**",
        "src/modules/**/constants.ts",
        "src/shared/ui/**",
        "src/shared/presentation/**",
        "src/shared/types/**",
        "src/infrastructure/monitoring/**",
        "src/infrastructure/server/**",
        "src/infrastructure/ai-providers/api-config/server*.ts",
        "src/infrastructure/ai-providers/api-config/init.ts",
        "src/infrastructure/ai-providers/api-config/migrate.ts",
        "src/infrastructure/ai-providers/api-config/templates.ts",
        "src/infrastructure/ai-providers/multi-api.ts",
        "src/infrastructure/ai-providers/enhanced-video.ts",
        "src/infrastructure/ai-providers/video-service.ts",
        "src/infrastructure/ai-providers/video.ts",
        "src/infrastructure/ai-providers/text.ts",
        "src/infrastructure/ai-providers/utils.ts",
        "src/infrastructure/ai-providers/services.ts",
        "src/infrastructure/ai-providers/outfit-synthesis.ts",
        "src/infrastructure/ai-providers/image-normalization.ts",
        "src/infrastructure/ai-providers/offline-queue.ts",
        "src/infrastructure/ai-providers/config.ts",
        "src/infrastructure/network/**",
        "src/infrastructure/api/**",
        "src/infrastructure/database/**",
        "src/shared/hooks/use-global-keyboard-actions.ts",
        "src/shared/hooks/useKeyboardShortcuts.ts",
        "src/shared/hooks/use-memory-monitor.ts",
        "src/shared/hooks/use-network-monitor.ts",
        "src/shared/hooks/use-current-time.ts",
        "src/shared/utils/performance.ts",
        "src/shared/utils/confirm.tsx",
        "src/shared/utils/file-download.ts",
        "src/shared/video-utils/video-frame-extractor.ts",
        "src/modules/**/hooks/use-*.ts",
        "src/modules/persistence/hooks/**",
        "src/modules/video/task-management/hooks/internals/*.ts",
        "src/modules/shot/shot-generation/**",
        "src/modules/shot/shot-reference/**",
        "src/modules/shot/element-binding/useElementBinding.ts",
        "src/modules/shot/feature-extraction/**",
        "src/modules/story/generation/services/style-guide-service.ts",
        "src/modules/story/planning/hooks/useStoryPlanner.ts",
        "src/modules/story/beat-editor/hooks/useAssetLoader.ts",
        "src/modules/story/prompt-editor/hooks/**",
        "src/modules/story/template/story-templates.ts",
        "src/modules/asset/hooks/**",
        "src/modules/sync/engine/server-store.ts",
        "src/modules/video/recovery/services/video-recovery.ts",
        "src/modules/video/cache/services/image-cache.ts",
        "src/infrastructure/storage/import-export.ts",
        "src/infrastructure/storage/storyboard.ts",
        "src/infrastructure/storage/templates.ts",
        "src/infrastructure/storage/sessions.ts",
        "src/infrastructure/storage/versions.ts",
        "src/infrastructure/storage/image-cache.ts",
        "src/infrastructure/storage/auto-save.ts",
        "src/infrastructure/storage/error-logs.ts",
        "src/infrastructure/di/container.ts",
        "src/infrastructure/di/registry.ts",
        "src/infrastructure/ai-providers/api-config/storage.ts",
        "src/infrastructure/ai-providers/config-status.ts",
        "src/infrastructure/ai-providers/providers/cloud-providers.ts",
        "src/infrastructure/storage/characters.ts",
        "src/infrastructure/storage/characters/parser.ts",
        "src/infrastructure/storage/collections.ts",
        "src/infrastructure/storage/core.ts",
        "src/infrastructure/storage/elements/queries.ts",
        "src/infrastructure/storage/stories.ts",
        "src/infrastructure/storage/stories/relations.ts",
        "src/infrastructure/storage/video-tasks.ts",
        "src/infrastructure/storage/video-tasks/bulk-operations.ts",
        "src/infrastructure/storage/video-tasks/parser.ts",
        "src/domain/schemas/character.ts",
        "src/domain/schemas/media.ts",
        "src/domain/services/reference-resolver.ts",
        "src/domain/types/sync.ts",
        "src/domain/utils/beat-prompt-builder.ts",
        "src/modules/prompt/builder/prompt-builder.ts",
        "src/modules/prompt/builder/quick-mode.ts",
        "src/modules/prompt/video/services/video-prompt-service.ts",
        "src/modules/shot/element-binding/element-manager.ts",
        "src/modules/video/task-management/services/video-tracker.ts",
        "src/shared/hooks/useDebouncedState.ts",
        "src/shared/sql-safety/schema-registry.ts",
        "src/shared/video-utils/video-codec.ts",
        "src/shared/video-utils/provider-codecs.ts",
        "src/config/constants.ts",
      ],
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
        perFile: true,
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
