export const BLOB_URL_REVOKE_DELAY_MS = 5000;
export const BLOB_URL_LONG_REVOKE_DELAY_MS = 10000;
export const COPY_RESET_DELAY_MS = 2000;
export const BATCH_OPERATION_INTERVAL_MS = 500;
export const CACHE_RETRY_INTERVAL_MS = 1000;
