/**
 * 内置高质量提示词模板库
 *
 * 来源：
 * - PromptHero / Civitai / LiblibAI / 吐司 TusiArt / PromptBase / FlowGPT 等社区精选
 * - 视频提示词来源于「全球顶级 AI 提示词合集」(评分 84+)
 * - 风格美学来源于「国风美学 AI 提示词库」
 * - 负面提示词来源于 Stable Diffusion 社区最佳实践
 * - 角色/场景模板基于项目现有 prompt-service 提炼
 *
 * 所有内置模板 id 以 "builtin_" 前缀，builtin=true，不可删除。
 */

import type { PromptTemplate } from "./prompt-template-types";

const now = Date.now();

/** 内置模板列表（24 个） */
export const BUILTIN_TEMPLATES: PromptTemplate[] = [
  // ========== 视频生成模板（10 个，来源于全球顶级 AI 提示词合集） ==========
  {
    id: "builtin_video_wuxia_flight",
    name: "仙侠御剑飞行",
    description: "国风仙侠风格，仙人御剑飞行场景，飘逸长袍+樱花+雾山",
    category: "video",
    target: "video",
    styleTags: ["wuxia", "chinese", "fantasy"],
    modelTags: [],
    content:
      "Chinese wuxia style, immortal flying on sword, flowing robes, cherry blossom petals swirling, misty mountains background, ethereal lighting, traditional ink painting aesthetic, 8k ultra detailed",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "LiblibAI",
    rating: 95,
  },
  {
    id: "builtin_video_porcelain",
    name: "国潮青花瓷",
    description: "中国传统青花瓷产品展示，微距+影棚光线",
    category: "video",
    target: "video",
    styleTags: ["chinese", "product"],
    modelTags: [],
    content:
      "Traditional Chinese blue and white porcelain, elegant patterns rotating, soft studio lighting, macro detail shot, cultural heritage aesthetic, minimalist composition, 4k product video",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "吐司 TusiArt",
    rating: 93,
  },
  {
    id: "builtin_video_slow_motion",
    name: "慢动作升格",
    description: "120fps 慢动作，戏剧性动作捕捉，情感冲击",
    category: "video",
    target: "video",
    styleTags: ["cinematic", "action"],
    modelTags: [],
    content:
      "Slow motion 120fps, time stretched moments, dramatic action capture, fluid movement details, cinematic slow-mo, high speed camera, emotional impact",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "Civitai",
    rating: 93,
  },
  {
    id: "builtin_video_god_rays",
    name: "体积光丁达尔效应",
    description: "神圣场景光束穿透雾尘，空灵氛围",
    category: "video",
    target: "both",
    styleTags: ["cinematic", "atmospheric"],
    modelTags: [],
    content:
      "Volumetric god rays, tyndall effect, light beams through fog or dust, atmospheric perspective, ethereal mood, cinematic lighting, divine atmosphere",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "吐司 TusiArt",
    rating: 92,
  },
  {
    id: "builtin_video_tracking_shot",
    name: "好莱坞追踪镜头",
    description: "动态追踪跟拍，35mm 镜头，专业调色",
    category: "video",
    target: "video",
    styleTags: ["cinematic", "camera"],
    modelTags: [],
    content:
      "Dynamic tracking shot following the subject, smooth gimbal movement, cinematic depth of field, 35mm lens, shallow focus transition from foreground to background, professional color grading, Arri Alexa quality",
    variables: [
      { name: "subject", description: "追踪主体描述", required: true },
    ],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "PromptHero",
    rating: 92,
  },
  {
    id: "builtin_video_golden_hour",
    name: "黄金时刻人像",
    description: "黄金时刻光线，温暖侧光，梦幻散景",
    category: "video",
    target: "both",
    styleTags: ["portrait", "cinematic"],
    modelTags: [],
    content:
      "Golden hour portrait, warm sunlight from side, soft fill light, hair rim glow, dreamy bokeh background, skin texture detail, cinematic color science, portrait mode f/1.8",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "FlowGPT",
    rating: 91,
  },
  {
    id: "builtin_video_portal_effect",
    name: "传送门特效",
    description: "科幻传送门，能量漩涡，维度裂缝",
    category: "video",
    target: "video",
    styleTags: ["scifi", "vfx"],
    modelTags: [],
    content:
      "Portal gateway effect, swirling energy vortex, dimensional rift, magical teleportation, sci-fi stargate, glowing runes, interdimensional travel, fantasy technology",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "PromptHero",
    rating: 90,
  },
  {
    id: "builtin_video_explosion",
    name: "爆炸冲击波",
    description: "动作电影级爆炸，碎片飞舞，慢动作",
    category: "video",
    target: "video",
    styleTags: ["action", "vfx"],
    modelTags: [],
    content:
      "Explosion shockwave effect, debris flying, fire and smoke, dramatic impact, action movie quality, slow motion debris, epic destruction, cinematic VFX",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "PromptHero",
    rating: 89,
  },
  {
    id: "builtin_video_cyberpunk_city",
    name: "赛博朋克未来都市",
    description: "霓虹浸染街道，全息广告，反乌托邦氛围",
    category: "video",
    target: "both",
    styleTags: ["cyberpunk", "scifi"],
    modelTags: [],
    content:
      "Cyberpunk futuristic city, towering skyscrapers, holographic advertisements, flying vehicles, neon soaked streets, dystopian atmosphere, blade runner inspired, high tech low life",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "Civitai",
    rating: 91,
  },
  {
    id: "builtin_video_steampunk",
    name: "蒸汽朋克机械",
    description: "黄铜齿轮旋转，维多利亚时代美学",
    category: "video",
    target: "both",
    styleTags: ["steampunk", "fantasy"],
    modelTags: [],
    content:
      "Steampunk machinery, brass gears rotating, steam vents, Victorian era aesthetic, warm amber lighting, intricate mechanical details, industrial fantasy, clockwork animation",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "LiblibAI",
    rating: 84,
  },

  // ========== 风格美学模板（4 个） ==========
  {
    id: "builtin_style_vintage_film",
    name: "复古胶片质感",
    description: "35mm 胶片颗粒，暖色调色，1970年代怀旧",
    category: "style",
    target: "both",
    styleTags: ["vintage", "retro"],
    modelTags: [],
    content:
      "Vintage film aesthetic, 35mm film grain, warm color grading, light leaks, nostalgic mood, 1970s look, analog photography feel, timeless classic",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "PromptHero",
    rating: 88,
  },
  {
    id: "builtin_style_fairy_tale",
    name: "童话梦幻风格",
    description: "魔法森林，柔和粉彩，异想天开氛围",
    category: "style",
    target: "both",
    styleTags: ["fantasy", "dreamy"],
    modelTags: [],
    content:
      "Fairy tale dreamy style, magical forest, soft pastel colors, sparkling effects, whimsical atmosphere, storybook aesthetic, enchanting mood, childhood wonder",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "Civitai",
    rating: 85,
  },
  {
    id: "builtin_style_minimalist",
    name: "极简主义美学",
    description: "干净线条，留白空间，现代设计",
    category: "style",
    target: "both",
    styleTags: ["minimalist", "modern"],
    modelTags: [],
    content:
      "Minimalist aesthetic, clean lines, negative space, monochromatic palette, modern design, less is more, architectural simplicity, zen philosophy",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "PromptBase",
    rating: 86,
  },
  {
    id: "builtin_style_gothic",
    name: "暗黑哥特风格",
    description: "中世纪建筑，戏剧性阴影，神秘氛围",
    category: "style",
    target: "both",
    styleTags: ["gothic", "dark"],
    modelTags: [],
    content:
      "Dark gothic aesthetic, medieval architecture, dramatic shadows, mysterious atmosphere, Victorian mourning, ornate details, macabre beauty, horror elegance",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "FlowGPT",
    rating: 83,
  },

  // ========== 角色生成模板（3 个，带变量插槽） ==========
  {
    id: "builtin_character_anime_portrait",
    name: "动漫角色立绘",
    description: "动漫风格角色立绘，带变量插槽（名字/发色/瞳色/服装）",
    category: "character",
    target: "image",
    styleTags: ["anime"],
    modelTags: [],
    content:
      "(anime style:1.3), (character portrait:1.2), 1girl, solo, {{character.name}}, {{character.hair_color}} hair, {{character.eye_color}} eyes, wearing {{character.outfit}}, smiling expression, youthful, big eyes, colorful, official art, unity 8k wallpaper, ultra detailed, beautiful and aesthetic, masterpiece",
    negativePrompt: "(worst quality, low quality:1.4), bad anatomy, deformed, ugly, blurry, watermark, text, signature",
    variables: [
      { name: "character.name", description: "角色名字或简短描述", required: true, defaultValue: "a young girl" },
      { name: "character.hair_color", description: "发色（如 silver/pink/black）", required: true, defaultValue: "silver" },
      { name: "character.eye_color", description: "瞳色（如 blue/red/green）", required: true, defaultValue: "blue" },
      { name: "character.outfit", description: "服装描述", required: true, defaultValue: "school uniform" },
    ],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "Stable Diffusion 社区",
    rating: 90,
  },
  {
    id: "builtin_character_cinematic_realistic",
    name: "电影级写实人像",
    description: "写实风格电影级人像，黄金时刻光线",
    category: "character",
    target: "image",
    styleTags: ["realistic", "cinematic"],
    modelTags: [],
    content:
      "Cinematic portrait of {{character.name}}, {{character.age}} years old, {{character.ethnicity}}, {{character.hair_style}}, wearing {{character.outfit}}, golden hour lighting, soft rim light, shallow depth of field f/1.8, skin texture detail, professional color grading, Arri Alexa quality, 8k hyper detailed",
    negativePrompt: "blurry, low quality, distorted, deformed, ugly, bad anatomy, watermark, text, plastic skin, overexposed",
    variables: [
      { name: "character.name", description: "角色名字或描述", required: true },
      { name: "character.age", description: "年龄", required: true, defaultValue: "25" },
      { name: "character.ethnicity", description: "族裔（如 East Asian/Caucasian）", required: true, defaultValue: "East Asian" },
      { name: "character.hair_style", description: "发型描述", required: true, defaultValue: "short black hair" },
      { name: "character.outfit", description: "服装", required: true, defaultValue: "elegant dress" },
    ],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "PromptHero",
    rating: 91,
  },
  {
    id: "builtin_character_cyberpunk",
    name: "赛博朋克角色",
    description: "赛博朋克风格角色，霓虹雨夜",
    category: "character",
    target: "image",
    styleTags: ["cyberpunk", "scifi"],
    modelTags: [],
    content:
      "A hyper-detailed portrait of {{character.name}}, confident and calm expression, cyberpunk style: neon-lit rainy city street background, holographic reflections, {{character.hair_color}} hair with cybernetic implants, wearing {{character.outfit}} with LED accents, glowing {{character.eye_color}} eyes, blade runner inspired, dystopian atmosphere, 8k cinematic",
    negativePrompt: "(worst quality, low quality:1.4), deformed, bad anatomy, ugly, blurry, watermark, text, signature, modern clean background",
    variables: [
      { name: "character.name", description: "角色描述", required: true, defaultValue: "a 30-year-old man" },
      { name: "character.hair_color", description: "发色", required: true, defaultValue: "neon blue" },
      { name: "character.eye_color", description: "瞳色", required: true, defaultValue: "glowing cyan" },
      { name: "character.outfit", description: "服装", required: true, defaultValue: "techwear jacket" },
    ],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "Civitai",
    rating: 89,
  },

  // ========== 场景生成模板（3 个，带变量插槽） ==========
  {
    id: "builtin_scene_wuxia_mountain",
    name: "仙侠山脉场景",
    description: "水墨风格仙侠山脉，云雾缭绕",
    category: "scene",
    target: "image",
    styleTags: ["wuxia", "chinese"],
    modelTags: [],
    content:
      "Chinese wuxia style landscape, towering misty mountains, {{scene.weather}}, traditional ink painting aesthetic, ethereal lighting, cherry blossom petals, ancient pavilion on cliff, flowing waterfall, {{scene.time_of_day}}, 8k ultra detailed, cinematic wide shot",
    negativePrompt: "modern buildings, western style, low quality, blurry, text, watermark",
    variables: [
      { name: "scene.weather", description: "天气（如 misty/clear/stormy）", required: true, defaultValue: "misty" },
      { name: "scene.time_of_day", description: "时间（如 dawn/noon/sunset/night）", required: true, defaultValue: "dawn" },
    ],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "LiblibAI",
    rating: 92,
  },
  {
    id: "builtin_scene_cyberpunk_street",
    name: "赛博朋克街道",
    description: "霓虹灯街道，全息广告，雨夜",
    category: "scene",
    target: "image",
    styleTags: ["cyberpunk", "scifi"],
    modelTags: [],
    content:
      "Cyberpunk futuristic city street at night, towering skyscrapers, holographic advertisements, neon signs reflecting on wet pavement, flying vehicles, light rain, dystopian atmosphere, blade runner inspired, {{scene.lighting}} lighting, cinematic wide angle, 8k ultra detailed",
    negativePrompt: "daytime, rural, clean streets, low quality, blurry, text, watermark",
    variables: [
      { name: "scene.lighting", description: "光照描述（如 neon blue/warm orange）", required: true, defaultValue: "neon blue and pink" },
    ],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "Civitai",
    rating: 90,
  },
  {
    id: "builtin_scene_fantasy_forest",
    name: "奇幻森林",
    description: "魔法森林，发光植物，神秘氛围",
    category: "scene",
    target: "image",
    styleTags: ["fantasy", "dreamy"],
    modelTags: [],
    content:
      "Enchanted fantasy forest, bioluminescent plants glowing in {{scene.glow_color}}, ancient towering trees, mystical fog, magical particles floating, winding path, {{scene.mood}} atmosphere, soft volumetric lighting, fairy tale aesthetic, 8k ultra detailed, cinematic",
    negativePrompt: "modern, urban, dead forest, low quality, blurry, text, watermark",
    variables: [
      { name: "scene.glow_color", description: "发光颜色（如 blue/purple/golden）", required: true, defaultValue: "blue and purple" },
      { name: "scene.mood", description: "氛围（如 mysterious/peaceful/eerie）", required: true, defaultValue: "mysterious" },
    ],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "Civitai",
    rating: 87,
  },

  // ========== 负面提示词模板（4 个） ==========
  {
    id: "builtin_negative_universal",
    name: "通用负面提示词",
    description: "适用于大多数图片/视频生成的通用负面提示词",
    category: "negative",
    target: "both",
    styleTags: [],
    modelTags: [],
    content: "blurry, low quality, worst quality, distorted, deformed, ugly, bad anatomy, watermark, text, signature, jpeg artifacts, lowres, cropped",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "Stable Diffusion 社区",
    rating: 95,
  },
  {
    id: "builtin_negative_anime",
    name: "动漫专用负面提示词",
    description: "动漫风格生成专用，避免常见动漫生成缺陷",
    category: "negative",
    target: "image",
    styleTags: ["anime"],
    modelTags: [],
    content: "(worst quality, low quality:1.4), (monochrome:1.1), (grayscale:1.1), bad anatomy, deformed, ugly, blurry, watermark, text, signature, bad hands, extra fingers, missing fingers, 6 fingers, bad proportions, lowres, cropped, worst quality, bad-artist, bad-artist-anime",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "Civitai 动漫社区",
    rating: 93,
  },
  {
    id: "builtin_negative_realistic",
    name: "写实专用负面提示词",
    description: "写实风格生成专用，避免塑料感和过度美化",
    category: "negative",
    target: "image",
    styleTags: ["realistic"],
    modelTags: [],
    content: "(worst quality, low quality:1.4), plastic skin, over-smoothed, overexposed, bad anatomy, deformed, ugly, blurry, watermark, text, signature, CGI, 3D render, cartoon, anime, illustration, painting, drawing, sketch, CGI, plastic, doll-like, porcelain skin",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "PromptHero",
    rating: 90,
  },
  {
    id: "builtin_negative_video",
    name: "视频专用负面提示词",
    description: "视频生成专用，避免抖动和画质问题",
    category: "negative",
    target: "video",
    styleTags: [],
    modelTags: [],
    content: "blurry, low quality, worst quality, distorted, deformed, flickering, jitter, choppy motion, watermark, text, signature, static frame, no motion, excessive motion, warped, morphed",
    variables: [],
    builtin: true,
    createdAt: now,
    updatedAt: now,
    source: "视频生成社区",
    rating: 88,
  },
];
